### ISSUE TITLE
[Feature] Add an Input for dates with date-picker support

### ISSUE THREAD

**Issue by SDP190** [fateh999/react-native-paper-form-builder#11]
Hi, great library, would like to know if its possible to use a date\time picker for a date field? and how?

**Comment by fateh999** [comment]
@SDP190 right now it is not but i can add support for date and time picker.

**Comment by fateh999** [comment]
@SDP190 I have added support for adding custom components within the formbuilder in the latest update you can check that.

**Comment by SDP190** [comment]
@fateh999 Thank you!
