### ISSUE TITLE
Unexpected form values onSubmit

### ISSUE THREAD

**Issue by kelokchan** [fateh999/react-native-paper-form-builder#14]
I'm trying to run the example shown on the last section of README but when I input some text to the input fields, I get yellow warning and when I console.log my `form.onSubmit` values, the response I get it this

```
{
  "email": {
    "dispatchConfig": null,
    "_targetInst": null,
    "_dispatchListeners": null,
    "_dispatchInstances": null,
    "nativeEvent": null,
    "type": null,
    "target": null,
    "eventPhase": null,
    "bubbles": null,
    "cancelable": null,
    "defaultPrevented": null,
    "isTrusted": null
  },
  "password": {
    "dispatchConfig": null,
    "_targetInst": null,
    "_dispatchListeners": null,
    "_dispatchInstances": null,
    "nativeEvent": null,
    "type": null,
    "target": null,
    "eventPhase": null,
    "bubbles": null,
    "cancelable": null,
    "defaultPrevented": null,
    "isTrusted": null
  }
}
```

I'm expecting something like
`
{ "email": "123@gmail.com", "password": "123" }
`

Did I set it up wrongly? 

```
"react-hook-form": "^6.8.3",
"react-native-paper-form-builder": "^1.0.9",
```

**Comment by bjkuncoro** [comment]
i have the same issue, is anything wrong with my code, my code it just copy paste from readme example

**Comment by fateh999** [comment]
Can you try with react hook form version 6.3.0 , I think there has been a change to the react hook form library. I will be fixing that, in mean time try to run from this version as in the example folder.

**Comment by bjkuncoro** [comment]
> Can you try with react hook form version 6.3.0 , I think there has been a change to the react hook form library. I will be fixing that, in mean time try to run from this version as in the example folder. @bjkuncoro @kelokchan

i try it using react-hook-form@6.3.0, but still get same problem, is there any step i missed when change react-hook-form version ?
<img width="396" alt="Screen Shot 2020-10-03 at 09 59 31" src="https://user-images.githubusercontent.com/21053587/94981806-69cce600-055f-11eb-8b27-619fdad43a4e.png">

**Comment by bjkuncoro** [comment]
Now im using react-hook-form V5.7.2 and problem solve, the problem happen because  of <Controlller/> API have different props handling between v5 and V6

**Comment by kelokchan** [comment]
Is this possible to have this library support `react-hook-form@6` ?

**Comment by fateh999** [comment]
@kelokchan  Sure will be only focussing on latest version of react-hook-form with next update this weekend to avoid these issues, but it might also cause backward incompatibility with older versions
