### ISSUE TITLE
Autocomplete onChange or onSelect

### ISSUE THREAD

**Issue by temuccio** [fateh999/react-native-paper-form-builder#16]
Hi all, 
I have 3 element of form.
The first element is autocomplete. When I select one element of autocomplete, I need to call a POST request for get data can will put in 2nd and 3th elements.
How I can execute this functions? Do you have a call onSelect or onChange?
My autocomplete fields is named prest.
I have try with this code:
`
useEffect(()=> {
    console.log(form.watch('prest'));
  },[]);
`
but it can't show the difference when I select different elements.

**Comment by fateh999** [comment]
For this, you can use this
`
useEffect(()=>{
//Api call
},[form.watch('keyname')])
`

**Comment by temuccio** [comment]
Nice, 
it works fine!
Thanks!!!
