### ISSUE TITLE
Style autocomplete 

### ISSUE THREAD

**Issue by temuccio** [fateh999/react-native-paper-form-builder#17]
Hi all, 
I use autocomplete type and I'm very happy for works.
Exist a method to style the "Dropdown" windows opened when I press on the field?
Can I change text "Search"?
Sorry but I don't find a solution

**Comment by fateh999** [comment]
Thanks, I am not sure about what do you mean by Dropdown windows can you elaborate, but for changing text will add a prop for it in next update in 3-4 days.

**Comment by temuccio** [comment]
I would like to style this windows (for example width, height, backgroundColor, border....)
![immagine](https://user-images.githubusercontent.com/571582/95449143-a421f300-0964-11eb-8e8a-e9dd01649bb3.png)

**Comment by fateh999** [comment]
Ok will add a style object to handle the Autocomplete modal in next update.

**Comment by temuccio** [comment]
Good...I suggest you to handle also select and each element can open another windows.

**Comment by temuccio** [comment]
Good...I suggest you to handle also select and each element can open another windows.

**Comment by temuccio** [comment]
Hi @fateh999 , can I help you to improve this for the update? I look forward this functionality
