### ISSUE TITLE
Select not load dynamic data

### ISSUE THREAD

**Issue by temuccio** [fateh999/react-native-paper-form-builder#18]
Hi, 
I use a select that load dynamic data (managed with useState()), such as:
```
{
   type: 'select',
   name: 'select',
   label: 'select',
   options: listselect,
    variant: 'flat'
},
```
If I change type 'select' with 'autocomplete', it's load correctly data.
It is normal?

**Comment by visharma14** [comment]
@temuccio can u please share your code example for me to achieve dyanmically load api data on option
