### ISSUE TITLE
Getting Possible `Unhandled Promise Rejection (id:0):` for 'select' type!!

### ISSUE THREAD

**Issue by Satyam-code143** [fateh999/react-native-paper-form-builder#30]
I am trying to add a  `select` type in my form and the TextInput appears but after clicking it I get a warning  `Unhandled Promise Rejection (id:0):` and the items do not display. Any solution for the same!! 
_(Used the code from the **Advance Examples** from the documentation)_

Thank you!!

**Comment by Satyam-code143** [comment]
My bad didn't wrap it with the provider!!

**Comment by fateh999** [comment]
Can you share your versions of react-native-paper and react-hook-form ?
