### ISSUE TITLE
Any way to specify the width of a column?

### ISSUE THREAD

**Issue by dk253** [fateh999/react-native-paper-form-builder#37]
Hey, I very much appreciate your work on this.

Is there any way to specify the width of a column, or is it just equal percents for the columns?

For example, I have City, State, Postal code columns.  I'd like to give the city 50% and the state and postal 20% and 30% respectively.

Thanks!

**Comment by fateh999** [comment]
Thanks, for now it is equivalent size but will provide an option of variable sized column in next update

**Comment by fateh999** [comment]
@dk253 added a flex prop in the config object, use it to manipulate width.

**Comment by dk253** [comment]
Excellent!  Thanks!!
