### ISSUE TITLE
Request for 'number' support

### ISSUE THREAD

**Issue by dk253** [fateh999/react-native-paper-form-builder#38]
Once again, I have to thank you for this!

Can I humbly request support for the 'number' type that is supported by the underlying react-hook-form?  I may be missing a way to do this, but it sure would be helpful.

Thanks!

D

**Comment by fateh999** [comment]
Can you let me know the detail use case ? Or you want the keyboard to be numeric as that can be done using keyboardType prop as numeric in textInputProps? As TextInput in react native only returns string even when entering numbers.

**Comment by dk253** [comment]
Thanks for your patience.  It would be nice to set the min and max rules associated with the 'number' fields like in react-hook-form.  With just text input I can limit what people type in.  For example, I have a field for the year that I need to not exceed the current year.

**Comment by fateh999** [comment]
Actually you can easily do that just with existing version, using validate rule in rules object.
