### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by Reszkettle** [fateh999/react-native-paper-form-builder#48]
Whenever i try to clear the `InputText` field by simply holding remove button, after the button is released I get the following error:
```
Error: Text strings must be rendered within a <Text> component.

This error is located at:
    in InputText (at Logic.js:18)
    in Logic (at FormBuilder.js:89)
    in FormBuilder (at IngredientForm.tsx:97)
```

**Comment by jenswegar** [comment]
Maybe check that your rules structure is correct for all inputs? A gotcha I stumbled upon was that the rule structure needs to include the error message, but react-hook-form validator allows both scalar values and object structure for rules (according to the typescript bindings at least).

This fails as a rule to formConfigArray:
`
rules: {
  minLength: 5
},
`

This works:
```
rules: {
  minLength: {
    value: 5,
    message: 'This works',
  },
},
```

The fix in this library could be to ensure the structure of the value coming in from the prop, and providing some default for the message if it doesn't exist...

**Comment by Reszkettle** [comment]
@jenswegar, thanks a lot .
I forgot to put a message in `required` rule object.

**Comment by Reszkettle** [comment]
@jenswegar I also think that there should be some default message, especially for `required` rule, like **This field is required**.
