### ISSUE TITLE
Autocomplete does not update displayValue in useEffect

### ISSUE THREAD

**Issue by shamilovtim** [fateh999/react-native-paper-form-builder#9]
I'm trying to get the AutoComplete to work by itself but I have an issue here:
```javascript
  useEffect(() => {
    if (watch(name) === '') {
      return setDisplayValue('');
    } else {
      triggerValidation(name);
    }
    const activeOption = options.find((option: Option) => option.value === watch(name));
    setDisplayValue(activeOption?.label);
  }, [watch(name)]);
```

The useEffect never updates the displayValue, so the original textinput is never updated and stays empty. Not sure what I'm doing wrong, other than I didn't supply a default value. However even tapping an option doesn't do anything. 

I have even tried to do a simple useEffect:
```javascript
 useEffect(() => {
    setDisplayValue('test');
  }, []);
```

regardless of that the component does nothing and does not show the state.

Here is the component:
` <Input editable={false} error={error} pointerEvents={'none'} {...props} value={displayValue} />`

If I change value='blahblahlbah' then the component will show that string. No clue what's going on. 

![Screen Recording 2020-04-11 at 3 49 00 AM](https://user-images.githubusercontent.com/3495974/79038526-f184f980-7ba7-11ea-9c4a-1d8930724f02.gif)

**Comment by fateh999** [comment]
@shamilovtim can you share an expo snack so that i can debug this issue.

**Comment by shamilovtim** [comment]
@fateh999 https://snack.expo.io/Yyd7W3i35

**Comment by shamilovtim** [comment]
I think I found it. I substituted TextInput from RN instead of RNMTF. Looks like material textfield is incompatible with this form. There seems to be a variable / prop collision, probably from setValue. It works fine with plain old react-hook-form.

**Comment by fateh999** [comment]
Actually you can use React Native Paper TextInput with mode='flat' , also you were missing the Controller Component from React Hook Form.

**Comment by shamilovtim** [comment]
Problem was coming from this pattern:
```
  const { options, name, watch, triggerValidation, label, Input, disabled, loadOptions, placeholder, error } = props;
```

```
<Input {...props}/>
```

To fix I manually added the props I needed to the input

I don't recommend sending all of the props into components like this, especially when you don't know what custom components the user is supplying. In my case the custom component I used had a variable collision with the props of this plugin.

**Comment by fateh999** [comment]
@shamilovtim thanks for the suggestion i will refactor the code to prevent this collision issue. Also i think i need to export individual inputs like Autocomplete so that it can be used without the form builder like in your case.

**Comment by shamilovtim** [comment]
Paper has nice text fields but I really like React Native Material Textfield so I don't use Paper for those
